function data = loadCartData(filename)
    load(filename);
    file = eval(filename);
    vars = file.Y;
    
    t = file.X(1).Data;    
    r = vars(14).Data;
    x1 = vars(1).Data;
    x1dot = vars(3).Data;
    x2 = vars(5).Data;
    x2dot = vars(7).Data;
    x3 = vars(9).Data;
    x3dot = vars(11).Data;
    K = [vars(2).Data(end), vars(6).Data(end)...
         vars(10).Data(end), vars(4).Data(end)...
         vars(8).Data(end), vars(12).Data(end)];
    V = vars(15).Data;
    Vcom = vars(13).Data;
    
    data = struct('t', t,...
                  'r', r,...
                  'x1', x1,...
                  'x1dot', x1dot,...
                  'x2', x2,...
                  'x2dot', x2dot,...
                  'x3', x3,...
                  'x3dot', x3dot,...
                  'K', K,...
                  'V', V,...
                  'Vcom', Vcom);
    
end

