function data = loadPendulumData(filename)
    load(filename);
    file = eval(filename);
    vars = file.Y;
    
    t = file.X(1).Data;    
    r = vars(6).Data;
    x = vars(1).Data;
    xdot = vars(3).Data;
    theta = vars(8).Data;    
    thetadot = vars(9).Data;
    K = [vars(2).Data(end), vars(7).Data(end)...
         vars(4).Data(end), vars(10).Data(end)];
    N = vars(5).Data(end);
    V = vars(11).Data;
    
    data = struct('t', t,...
                  'r', r,...
                  'x', x,...
                  'xdot', xdot,...
                  'theta', theta,...
                  'thetadot', thetadot,...
                  'K', K,...
                  'N', N,...
                  'V', V);    
end

